name: Deploy to Digitalocean Droplet
on: 
  workflow_dispatch:
  push:
    branches:
      - 'release'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            ls -al
