name: Deploy to Digitalocean Droplet
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/*"
          # target: "~/colab/colab-app"
          target: "/var/www/collab"
          rm: true
          strip_components: 1
